apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: retail-store-ingress-http-instance-mode
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: instance
    alb.ingress.kubernetes.io/load-balancer-name: retail-store-http-instance-mode
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
    alb.ingress.kubernetes.io/healthcheck-path: /actuator/health/readiness
    # alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-south-1:897722700244:certificate/a99a0eb7-12e2-42ea-a5ef-cbd0b0a6e46a
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '15'
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '5'
    alb.ingress.kubernetes.io/success-codes: '200'
    alb.ingress.kubernetes.io/healthy-threshold-count: '2'
    alb.ingress.kubernetes.io/unhealthy-threshold-count: '2'
    # External-Dns
    #external-dns.alpha.kubernetes.io/hostname: retailstore.cloudllearning.com
spec:
  ingressClassName: alb
  defaultBackend:
    service:
      name: ui-np
      port:
        number: 80