---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: catalog-db-secrets
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "rds!db-18993584-1ede-4bbc-b9bf-99bccbdb52f6"
        objectType: "secretsmanager"
        jmespath:
          - path: "username"
            objectAlias: "username"
          - path: "password"
            objectAlias: "password"
    usePodIdentity: "true"