---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: catalog-db-secrets
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "rds!db-04b88392-de7d-4385-b577-636d0f746382"
        objectType: "secretsmanager"
        jmespath:
          - path: "username"
            objectAlias: "username"
          - path: "password"
            objectAlias: "password"
    usePodIdentity: "true"